### ISSUE TITLE
Safari 浏览器中的样式兼容性问题

### ISSUE THREAD

**Issue by RichardTang2003** [g0dmao/hexo-theme-Klise-enhanced#1]
首先感谢继续维护主题,我也挺喜欢这个主题。
但是修改后的主题在 Safari 浏览器中出现宽度不够最后一个字换行显示,下面附有截图。
在iPhone iPad Mac上的Safari浏览器都会出现这个问题。
![Image](https://github.com/user-attachments/assets/64106cfa-5a68-4cf7-94a1-339b131b62b9)

**Comment by g0dmao** [comment]
感谢你的反馈！
由于我目前手头没有 iOS 或 macOS 设备，无法在真实的 Safari 浏览器下进行调试和验证，所以这个问题暂时难以定位和修复。

**Comment by RichardTang2003** [comment]
如果你想修的话可以参考一下我的fork。改的东西太多，就不pull request了。
主要的修复部分

1. 主页背景图会滚动的问题
```css
body::before {
  content: '';
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  z-index: -1;
  background: 
    linear-gradient(rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5)), 
    url('');
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
}

body[data-theme=dark]::before {
  background: 
    linear-gradient(rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5)), 
    url('');
  background-position: center center;
  background-repeat: no-repeat;
  background-size: cover;
}
```

2. 菜单栏换行问题
```css
.trigger-container {
  display: flex;
  flex-wrap: nowrap;
  min-width: 0;
}
.trigger-container .menu-link {
  white-space: nowrap;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
}
```
但是这样会让移动端也不换行，移动端的菜单栏要重写。
```css
@media screen and (max-width: 768px) {
  .trigger-container {
    flex-wrap: wrap; /* 允许换行 */
    flex-direction: column; /* 垂直排列 */
    align-items: stretch;   /* 拉伸到100%宽 */
  }
  .trigger-container .menu-link {
    white-space: normal;    /* 允许文本换行 */
    min-width: 0;
    overflow: visible;
    text-overflow: unset;
    width: 100%;            /* 每个菜单项占满一行 */
    display: block;
    box-sizing: border-box;
  }
}
```

4. 首页recent post的换行问题

加一行
```css
.post-item .post-item-title {
  flex: 1;
}
```

5. 文章tag会换行的问题
```css
.post-tags .tag {
  flex: auto;
  font-size: 0.8rem;
  color: #888;
  margin-right: 0.5rem;
  text-decoration: none;
  white-space: nowrap;    /* 不换行，防止断字 */
  word-break: keep-all;   /* 保持单词整体 */
  overflow-wrap: normal;
  display: inline-block;  /* 保证同行显示 */
  vertical-align: middle;
}
```

我也不是做前端的，不知道问题根源是什么，只能每个地方修修补补一下。
